<a href="https://colab.research.google.com/github/ahkhaider-10/Data-Science/blob/main/DATA_SCIENCE_NIELIT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#05 - 07 - 2022, Tuesday


In [ ]:
print("First day of training at NIELIT, Chandigarh. 05-07-2022")

First day of training at NIELIT, Chandigarh. 05-07-2022


#06 - 07 - 2022, Wednesday

In [ ]:
# WAP to find all arithmetic operations
a = 10
b = 5
print("Addition: ",a + b)
print("Multiplication: ",a * b)
print("Division: ",a / b)
print("Subtraction: ",a - b)


Addition:  15
Multiplication:  50
Division:  2.0
Subtraction:  5


In [ ]:
# WAP to swap two numbers 
a = 10
b = 20
print(f"Before swapping: a = {a}, b = {b}")
temp = a
a = b
b = temp
print(f"After swapping: a = {a}, b = {b}")


Before swapping: a = 10, b = 20
After swapping: a = 20, b = 10


In [ ]:
# WAP to calculate simple interest
p = int(input("Enter principle (Rs.): "))
r = int(input("Enter rate (%): "))
t = int(input("Enter time (yr): "))
SI = (p*r*t) / 100
print(f"Simple interest: {SI}")


Enter principle (Rs.): 100000
Enter rate (%): 8
Enter time (yr): 5
Simple interest: 40000.0


In [ ]:
# WAP 



#07 - 07 - 2022, Thursday

In [ ]:
# eval function
a = eval(input("Please enter an expression: "))
print(a)


Please enter an expression: 2 + 5 + 9
16


In [ ]:
# controlling print statement
a, b, c, d = 10, 20, 30, 40
print(a, b, c, d, sep = ':') # sep = seperator
print(a, b, c, d, sep = '-----')

10:20:30:40
10-----20-----30-----40


In [ ]:
# print is a function, we can assign it to other variables
my_print = print
my_print('This is through my_print')
print("let's see, if we get error or not")

This is through my_print
let's see, if we get error or not


In [ ]:
print("This is through print")


This is through print


In [ ]:
'''
Operators:
1. Binary
2. Unary
3. Ternary
'''


In [ ]:
# WAP to get the bigger of two numbers: 
x = int(input('Enter first number: '))
y = int(input('Enter second number: '))
if x > y:
  print(f'{x} is greater than {y}')
else:
  print(f'{y} is greater than {x}')



Enter first number: 4
Enter second number: 9
9 is greater than 4


In [ ]:
# Chech whether a number: is positive, is negative or zero, using 'if-elif-else'
num = float(input("Enter a number: "))
if num > 0:
  print('The number is positive.')
elif num == 0:
  print('The number is zero.')
else:
  print('The number is negative.')

Enter a number: 0
The number is zero.


In [ ]:
# WAP to check whether character is althabet or not:
ch = input('Enter the character(s): ')
if ch.isalpha():
  print('Alphabet')
else:
  print('Not an alphabet')

In [ ]:
# WAP Enter marks of maths, science,

In [ ]:
# WAP to display menu of choice and find sum or product accordingly:
choice = int(input('Enter you choice: '))
if choice == 1:
  a = int(input('enter first number: '))
  b = int(input('enter second number: '))
  



In [ ]:
# Factorial of a number:
f = 1
x = int(input('Enter the number: '))
while(x > 1):
  f = f * x
  x = x - 1 
print(f'Factorial of number = {f}') 

Enter the number: 7
Factorial of number = 5040


#Armstrong Number: 
A number is thought of as an Armstrong number if the sum of its own digits raised to the power number of digits gives the number itself. For example, 0, 1, 153, 370, 371, 407 are three-digit Armstrong numbers and, 1634, 8208, 9474 are four-digit Armstrong numbers and there are many more.

#Perfect Number:
perfect number, a positive integer that is equal to the sum of its proper divisors. The smallest perfect number is 6, which is the sum of 1, 2, and 3. Other perfect numbers are 28, 496, and 8,128.


#Sum of digits of a number:

In [ ]:
# Program to input a number and check armstrong.
num = int(input('Enter a number: '))
num = 8383
sum = 0
temp = num
while temp > 0:
  r = temp % 10
  sum = sum + (r**3)
  temp = temp / 10
if (num == sum):
    print("Armstrong number")
else:
    print("Not an armstrong number")

Enter a number: 153
Not an armstrong number


# 08 - 07 - 2022, Friday

In [ ]:
'''
Loops: for
'range' keyword:
range(10, 15, 1) = 10, 11, 12, 13, 14

'''
for j in range(1, 6):
  print(j, end = ",")

for j in range(0, 51, 5):
  print(j)
  print("hello")
print("done")

In [ ]:
# break, continue 
for i in range(1, 5, 1):
  continue
print(i)

for ch in "COMPUTER":
  if ch == "T":
    print(ch)
  

4
T


In [ ]:
i = 0
while i < 9:
  i = i + 1
  if i == 5:
    continue
  else:
    break


In [ ]:
# WAP to print pattern using nested 'for'
for i in range(1, 6):
  for j in range(1, 4):
    print(i, end = "   ")
  print("\n")


In [ ]:
# WAP to print a pyramid patter using 'for':
for i in range(1, 5):
  for j in range(1, i + 1):
    print(j, end = ' ')
  print(' ')

1  
1 2  
1 2 3  
1 2 3 4  


In [ ]:
# WAP to print a pyramid (inverted)
for i in range(6, 0, -1):
  for j in range(1, i + 1):
    print(j, end = ' ') # i or j
  print(' ')

In [ ]:
# WAP to print tables:
for i in range(1, 6):
  for j in range(1, 11):
    print(i, ' * ', j, ' = ', i * j)
  print('\n')
  

1  *  1  =  1
1  *  2  =  2
1  *  3  =  3
1  *  4  =  4
1  *  5  =  5
1  *  6  =  6
1  *  7  =  7
1  *  8  =  8
1  *  9  =  9
1  *  10  =  10


2  *  1  =  2
2  *  2  =  4
2  *  3  =  6
2  *  4  =  8
2  *  5  =  10
2  *  6  =  12
2  *  7  =  14
2  *  8  =  16
2  *  9  =  18
2  *  10  =  20


3  *  1  =  3
3  *  2  =  6
3  *  3  =  9
3  *  4  =  12
3  *  5  =  15
3  *  6  =  18
3  *  7  =  21
3  *  8  =  24
3  *  9  =  27
3  *  10  =  30


4  *  1  =  4
4  *  2  =  8
4  *  3  =  12
4  *  4  =  16
4  *  5  =  20
4  *  6  =  24
4  *  7  =  28
4  *  8  =  32
4  *  9  =  36
4  *  10  =  40


5  *  1  =  5
5  *  2  =  10
5  *  3  =  15
5  *  4  =  20
5  *  5  =  25
5  *  6  =  30
5  *  7  =  35
5  *  8  =  40
5  *  9  =  45
5  *  10  =  50




In [ ]:
# index positive or negative:
string = 'python'
print(string[1])
print(string[-1])
print(string[0])
print(string[-3])


y
n
p
h


In [ ]:
# String traversing:
c = 'Chandigarh'
for i in c:
  print('CH', end = ' ')

CH CH CH CH CH CH CH CH CH CH 

In [ ]:
# WAP to find length of a string:
x = input('Enter a string: ')
print('Length of string: ', len(x))
# count = 0
# for i in x:
#   count =+ 1
# print('Length of string: ', count)

Enter a string: ahk
Length of string:  3


In [ ]:
# WAP to determine prime numbers:
print(2, 3, 5, 7)
for i in range(2, 100):
  if i % 2 == 0 or i % 3 == 0 or i % 5 == 0 or i % 7 == 0:
    continue
  else:
    print(i)

In [ ]:
# Print the sum of resiprocals of first 100 natural nuumbers
sum = 0
for i in range(1, 101):
  rec = 1 / i
  sum = sum + rec
print('Sum of resiprocals of first 100 natural numbers: ', sum)

Sum of resiprocals of first 100 natural numbers:  5.187377517639621


In [ ]:
# Read 5 integer inputs from a user. Print the sum of only positive inputs.
mylist = []
sum = 0
for i in range(5):
  x = int(input('Enter the number: '))
  mylist.append(x)
for i in mylist:
  if i >= 0:
    sum = sum + i
print('The sum of positive inputs: ', sum)


Enter the number: 1
Enter the number: -8
Enter the number: 7
Enter the number: -9
Enter the number: 3
The sum of positive inputs:  11


In [ ]:
# WAP to display all string functions in one program : upper, capitalize, isalpha, i
mystring = 'haiDer = Lion'
print(mystring.upper())
print(mystring.lower())
print(mystring.capitalize())
print(mystring.isalpha())


HAIDER = LION
haider = lion
Haider = lion
False


In [ ]:
# Count the occurence of character in string
mystring = 'This is my string, we will find occurence of characters.'
print('c:', mystring.count('c'))
print('t:', mystring.count('t'))
print('s:', mystring.count('s'))
print('h:', mystring.count('h'))

c: 5
t: 2
s: 4
h: 2


#11-07-2022, Monday

In [ ]:
# ord() function returns the numeric value of char
# chr() function returns the character corresponding to ascii code
a = ord('A')
b = ord('Z')
c = chr(97)
d = chr(112)
e = chr(a)
print(a, 
      b, 
      c, 
      d,
      e)

In [ ]:
# slicing on strings:
str = "Portion"
#      0123456
#     -7.....-1
print('1 to 3', str[1:3])
print('2 to end', str[2:])
print('1 to -1', str[1:-1])
print('0 to -1', str[:-1])
print('-7 to -1', str[-7:-1])
print('Till end', str[0:7])


1 to 3 or
2 to end rtion
1 to -1 ortio
0 to -1 Portio
-7 to -1 Portio
Till end Portion


In [ ]:
name = 'Python Programming'
name[-12:1:-1]

' noht'

In [ ]:
s = 'Python Training'
for i in s:
  print(i + ' Welcome')

P Welcome
y Welcome
t Welcome
h Welcome
o Welcome
n Welcome
  Welcome
T Welcome
r Welcome
a Welcome
i Welcome
n Welcome
i Welcome
n Welcome
g Welcome


In [ ]:
str = 'chanDiGarh'
print(str.capitalize())
print(str.isupper())
print(str.upper())
print(str.lower())
print(str.islower())
print(str.isalpha())
print(str.isalnum())
print('Rcc@123'.isalnum()) # @ special character.
print('123400'.isalnum())
print('Abcd'.isdigit())
print('213345'.isdigit())


Chandigarh
False
CHANDIGARH
chandigarh
False
True
True
False
True
False
True


In [ ]:
title = 'Python Programming is Fun.'
print(title.casefold())
print(title.count('m')) # counting the occurence
print(title.find('y')) # to find the position of a character
print(title.find('C')) # find position of a character which is not present
print(title.endswith('Fun.')) # endswith function 

python programming is fun.
2
1
-1
True


In [ ]:
str = '  R  C  C  '
print('Original length', len(str))
str1 = str.lstrip()
print('Left strip: ', len(str1))
str2 = str.rstrip()
print('Right strip: ', len(str2)) 

Original length 11
Left strip:  9
Right strip:  9


In [ ]:
print(' '.isspace())
print('This Is Rcc'.istitle()) # title: initials of every word is capital.

True
True


In [ ]:
# replace(old, new)
str = 'NIELIT Chandigarh prior name was DOEACC Chandigarh.'
print(str.replace('DOEACC', 'RCC'))


NIELIT Chandigarh prior name was RCC Chandigarh.


In [ ]:
# string join:
str = 'CHD'
str1 = ('NIELIT', 'Ropar')
str3 = 'Chandigarh'
str2 = ' '
print(str + str2 + str3)

CHD Chandigarh


In [ ]:
# swapcase():
str = 'COMPUTER'
print(str.swapcase())

computer


In [ ]:
# partition():
str = 'The Golden Star.'
print(str.partition('Gold'))
print(str.partition('e'))
print(str.partition('a'))
print(str.partition(' '))
print(str.partition('r'))

('The ', 'Gold', 'en Star.')
('Th', 'e', ' Golden Star.')
('The Golden St', 'a', 'r.')
('The', ' ', 'Golden Star.')
('The Golden Sta', 'r', '.')


In [ ]:
# split():
str = 'Try try again until you succeed'
print(str.split())

['Try', 'try', 'again', 'until', 'you', 'succeed']


In [ ]:
# list declaration
L1 = [12, 45, 67, 89, 61]
city = ['Patiala', 'Sirhind', 'Tharki']
print(L1, '\n', city, end = '')

[12, 45, 67, 89, 61] 
 ['Patiala', 'Sirhind', 'Tharki']

In [ ]:
# List operations: 
# Joining List (+)
a = [1, 2, 3]
b = [4, 5, 6]
print(a + b)

# repeat operation
c = [11, 12]
print(c * 3)

# slicing list
L1 = ['a', 'b', 'c']
print(L1[1:2])

l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(l[1:7:2])

print(l[7:10])
print(l[0:9])
print(l[::3])
print(l[8:3:-1])
print(l[::-2])


In [ ]:
print(sum(list(range(1, 5))))
print(list(range(1, 10, 2)))
print(list(range(2, 5, 2)))


10
[1, 3, 5, 7, 9]
[2, 4]


In [ ]:
# WAP to replace a character in a string with symbol:
mystring = 'Haider'
print(mystring.replace('a', '@'))

H@ider


In [ ]:
# WAP to check whether string is palindrome or not
s = input('Enter the word, for which you wish to find palindrome: ')
if s == s[::-1]:
  print(f'{s} is Palindrome')
else:
  print(f'{s} is Not Palindrome')

Enter the word, for which you wish to find palindrome: ahk
ahk is Not Palindrome


In [ ]:
# WAP to count alphabets, digits and special characters in a string
s = input('Enter a string: ')
alpha = 0
dig = 0
spcl = 0
for i in s:
  if i.isalpha():
    alpha =+ 1
  elif i.isdigit():
    dig =+ 1
  else:
    spcl =+ 1
print('Number of alphabets: ', alpha)
print('Number of digits: ', dig)
print('Number of special characters: ', spcl)

Enter a string: haider
Number of alphabets:  1
Number of digits:  0
Number of special characters:  0


In [ ]:
# Program to input the elements in the list as per the count then find sum of elements.
n = int(input('Enter length of list: '))
l = []
a = int(input('If the elements are numeric, enter 0 otherwise 1: '))
for i in range(0, n):
  if a == 0:
    x = int(input('Enter the element: '))
    l.append(x)
  else:
    y = (input('Enter the element: '))
    l.append(y)

print(l)
if a == 0:
  print('Sum of elements of the list: ', sum(l))

In [ ]:
# Program to read the line and count the number of words in it
s = input('Enter a string: ')
c = 0
l = s.split()
for i in l:
  c = c + 1
print('Number of words:', c)

Enter a string: Ali Haider Khan
Number of words: 3


In [ ]:
# Program to find the sorted middle element in a random number list 
l = [1, 2, 43, 97, 6, 45, 12, 5]
m = ['m', 'h', 'c', 'd', 'z', 'f', 'b', 'a']
print(l)
l.sort()
print(l)
print(m)
m.sort()
print(m)

[1, 2, 43, 97, 6, 45, 12, 5]
[1, 2, 5, 6, 12, 43, 45, 97]
['m', 'h', 'c', 'd', 'z', 'f', 'b', 'a']
['a', 'b', 'c', 'd', 'f', 'h', 'm', 'z']


#12-07-2022, Tuesday

In [ ]:
# Traversing through a list of elements: 
# len(), count(), append(), extend(), insert(), pop(), remove(), sort(), del(), clear(), min(), max()
lst = [1, 2, 3, 4, 5, 6]
lst1 = [20, 30, 40, 50]
print(lst1.extend(lst))

None


In [ ]:
# Tuples

In [ ]:
# Packing and Unpacking

In [ ]:
# Tuple functions: cmp(), len(), max(), min(), count(), sorted(), index()
# cmp() compares both tuples and returns 0 if same, -1 if first is greater and 1 if second is greater
t = 33, 44, 55, 66, 77, 33, 55, 55, 77, 33
print(len(t))
print(t.count(33))
print(max(t))
print(min(t))
print(sorted(t))
print(t.index(33, 3)) # 3rd occurence
print(t.index(77))


10
3
77
33
[33, 33, 33, 44, 55, 55, 55, 66, 77, 77]
5
4


In [ ]:
# Tuple slicing syntax: [start index(included): stop index(excluded): steps]
# Tuple addition
# Tuple multiplication (repetition)
# Deleting a tuple as tuple cannot be changed so element cannot be deleted and will show error


In [ ]:
# List Comprehension
v1 = [2, 4, 6]
v2 = [4, 3, -9]
l = [x * y for x in v1 for y in v2]
m = [x + y for x in v1 for y in v2]
print(l)
print(m)

n = [v1[i] * v2[i] for i in range(len(v1))]
print(n)

[8, 6, -18, 16, 12, -36, 24, 18, -54]
[6, 5, -7, 8, 7, -5, 10, 9, -3]
[8, 12, -54]


In [ ]:
v1 = [2, 4, 6]
a = [3 * x for x in v1 if x > 3]
print(a)

[12, 18]


In [ ]:
# Pointers:
 
s = [5, 6, 3, 6, 1, 10]
t = s
t.append(69)
print('s:', s)
print('t:', t)

m = [1, 2, 3, 5, 5, 7, 9]
n = m[:]
n.append(69)
print('m:', m)
print('n:', n)

s: [5, 6, 3, 6, 1, 10, 69]
t: [5, 6, 3, 6, 1, 10, 69]
m: [1, 2, 3, 5, 5, 7, 9]
n: [1, 2, 3, 5, 5, 7, 9, 69]


In [ ]:
# Mutable vs Non-Mutable

In [ ]:
# Add a pair (x, y) in a list if for x in l1 its square y is present in l2
l1 = [1, 2, 3, 4, 5, 6]
l2 = [1, 4, 10, 17, 25, 36]
l = []
for i in l1:
  for j in l2:
    if i**2 == j:
      l.append((i, j))
    
print('Without list comprehension:', l) 
limst = [(x, y) for x in l1 for y in l2 if x**2 == y]
print('With list comprehension:', limst)

Without list comprehension: [(1, 1), (2, 4), (5, 25), (6, 36)]
With list comprehension: [(1, 1), (2, 4), (5, 25), (6, 36)]


In [ ]:
# WAP to enter names and marks of students and display information using dictionary
n = int(input('Enter the number of information set you desire to enter: '))
dic = {} 
for i in range(0, n):
  i = input('Enter the name: ')
  L = []
  for j in range(2):
    dic[i] = int(input('Enter the marks: '))
    L.append(dic[i])
  dic[i] = L
print(dic)

Enter the number of information set you desire to enter: 2
Enter the name: Haider
Enter the marks: 12
Enter the marks: 13
Enter the name: Maasha
Enter the marks: 12
Enter the marks: 18
{'Haider': [12, 13], 'Maasha': [12, 18]}


In [ ]:
# Write comprehension code for the below code:

fruits = ['apple', 'banana', 'cherry', 'kiwi', 'mango', 'ali', 'aalo']
'''
newlist = []
for x in fruits:
  if 'a' in x:
    newlist.append(x)
print(newlist)

'''
newlist = [x for x in fruits if x[0] == 'a']
print(newlist)

['apple', 'ali', 'aalo']


In [ ]:
# Count the frequency of items of list using dictionary
dic = {1: [1, 2, 3, 1, 5, 4, 3, 2, 1], 2: [1, 2, 3, 3, 4, 4]}
count = 0
for i in dic:
  for f in dic[i]:
    print(f)
    for m in range(len(dic[i])):
      if dic[i][0] == f:
        count = count + 1

print(count)

1
2
3
1
5
4
3
2
1
1
2
3
3
4
4
33


#13-07-2022, Wednesday
***PENDING***

In [ ]:
#Dictionary: Collection of key-value pair, unordered collection of data values, 
# used to store date values like a map, which unlike other Data Types that hold only single value as an element
mydic = {'Name': 'Ansh', 'city': 'Thakri', 'Phone': '12345'}
mydic

In [ ]:
# dict() function
# update() or assignment.
# Using list as a value for a key-value pair
# Nested dictionary

In [ ]:
# WAP to enter names and marks of students and display information using nested dictionary
n = int(input('Enter the number of information set you desire to enter: '))
dic = {} 
for i in range(0, n):
  i = input('Enter the name: ')
  subDic = {}
  for j in range(2):
    j = input('Enter the subject: ')
    # for h in range(1):
    subDic[j] = int(input('Enter the marks: '))
  dic[i] = subDic
print(dic)

In [ ]:
# Removing dictionary elements and dictionaries
d = {1: 'A', 2: 'B'}
print(d)
del d[2]
print(d)

{1: 'A', 2: 'B'}
{1: 'A'}


In [ ]:
# Dictionary functins and methods:
d = {1: 'aa', 2: 'bb', 3: 'cc'}
print(len(d))
print(d.get(5))
print(d.get(3))
d.pop(3)
print(3)
print(d.keys())
print(d.values())
print(d.items())

3
None
cc
3
dict_keys([1, 2])
dict_values(['aa', 'bb'])
dict_items([(1, 'aa'), (2, 'bb')])


In [ ]:
d = {1: 'Haider', 2: 'Ansh', 3: 'Hitesh'}
for i in d:
  print(d[i])

Haider
Ansh
Hitesh


In [ ]:
for i in d:
  print(i, '-->', d[i])

1 --> Haider
2 --> Ansh
3 --> Hitesh


In [ ]:
# Traversing:


In [ ]:
# File Processing:
# open(), close(), read(), write(), etc.

In [ ]:
# Functions: User defined, set of code which could be called again and again according to the requirement.

# Function argument: 1. Default, calling functino with default agruments
#                    2. Keyword arguments
#                    3. Positional arguments
#                    4. Variable length argument in functions


In [ ]:
# 4. Variable length argument:
def message(*var):
  print(type(var))
  print(var)
  for i in var:
    print(i)
message(1, 2, 4, 5, 6, 'string')

<class 'tuple'>
(1, 2, 4, 5, 6, 'string')
1
2
4
5
6
string


In [ ]:
def myAddUniversal (*args):
  s = 0 
  for i in range(len(args)): 
    s += args[i] # s = s+args[i]
  return s

print(myAddUniversal (2,4,5,4.6,78))

93.6


In [ ]:
def printAllVariableNamesAndValues (**args): 
  for x in args:
    print("Variable Name is :",x," And Value is :", args[x])

printAllVariableNamesAndValues(a = 3,b="B",c="CCC",y=6.7)

Variable Name is : a  And Value is : 3
Variable Name is : b  And Value is : B
Variable Name is : c  And Value is : CCC
Variable Name is : y  And Value is : 6.7


In [ ]:
# Scope of a variable:
x = 5
def print_num(y):
  x = 3
  print('y =', y)
  print('Inside, x =', x)
  return y

print('Outside x =', x)
print_num(4)
print('Outside again x =', x)

Outside x = 5
y = 4
Inside, x = 3
Outside again x = 5


In [ ]:
def maximum(a, b):
  if a > b:
    return a
  else: return b

def minimum(a, b):
  if a < b: return a
  else: return b

x = -1
x = maximum(3 + 6, 4)
print(x)
y = minimum(x, 9)
print(y)

9
9


In [ ]:
# global variable

In [ ]:
# Recursion:
def recursive_fibonacci(n):
  if n <= 1:
      return n
  else:
      return(recursive_fibonacci(n-1) + recursive_fibonacci(n-2))
 
n_terms = 10
 
# check if the number of terms is valid
if n_terms <= 0:
  print("Invalid input ! Please input a positive value")
else:
  print("Fibonacci series:")
for i in range(n_terms):
    print(recursive_fibonacci(i))

Fibonacci series:
0
1
1
2
3
5
8
13
21
34


In [ ]:
# Recursion:
def recursive_factorial(n):
  if n == 1:
      return n
  else:
      return n * recursive_factorial(n-1)
 
# user input
num = 6
 
# check if the input is valid or not
if num < 0:
  print("Invalid input ! Please enter a positive number.")
elif num == 0:
  print("Factorial of number 0 is 1")
else:
  print("Factorial of number", num, "=", recursive_factorial(num))

Factorial of number 6 = 720


In [ ]:
# Function to calculate reverse of a number:
n = int(input('Enter a number, you want to find reverse of: '))
s = str(n)
n = int(s[::-1])
print(n)

Enter a number, you want to find reverse of: 12456677
77665421


In [ ]:
# Function to calculate prime number or not:
num = int(input('How many numbers you want to test: '))
# for i in range(0, num):
#   n = int(input('Enter the number to find whether its prime or not: '))
#   if n == 1 or n == 0:
#     print(f'{n} is not a prime.')
#   elif n % n == 0 and n % 1 == n:
#     print(f'{n} is a prime.')
#   else:
#     print(f'{n} is composite.' )

In [ ]:
# Function to accept a string and calculate the number of upper case letter and lower:
s = input('Enter a string: ')
U_count, L_count = 0, 0
for i in s:
  if i.isupper():
    U_count = U_count + 1
  elif i.islower():
    L_count = L_count + 1
print('Number of Upper case letters:', U_count)
print('Number of Lower case letters:', L_count)

Enter a string: This Day is As BeaUtifuL as IT getS
Number of Upper case letters: 9
Number of Lower case letters: 19


#14-07-2022, Thursday

In [ ]:
#docstring
def printSuccess():
  """
  This function is doing nothing, except printing a message.
  That message is 'Hello'.

  """

help(printSuccess) #help function

Help on function printSuccess in module __main__:

printSuccess()
    This function is doing nothing, except printing a message.
    That message is 'Hello'.



In [ ]:
'''
Lambda function: Lambda Keyword is used to create small Anonymous function. 
These function are called anonymous because they are not declared as standard function.
Lamda forms can take any number of arguments but return one value.
They cannot contain commands or multiple expressions. 
syntax: lambda[arg1 [arg2,.....]]:expression.
'''
#function definition:
sum = lambda arg1, arg2: arg1 + arg2

#call sum function:
print("value of total is:", sum(10, 20))

value of total is: 30


In [ ]:
y=10
def inner():
  s = 4
  print("s:", s)
  print("y:", y)
inner()
#print(s) will show error as out of scope of function
print("outer y:", y)

s: 4
y: 10
outer y: 10


In [ ]:
y=10
def inner():
  s = 4
  global y
  y = y + 1
  #y=y+1 will show an error as cannot cahnge global var within function for this use of --global word
  print("y:", y)

inner()
#print(s) will show error as out of scope of function
print("outer y:", y)

y: 11
outer y: 11


In [ ]:
y = 10 # global
def outer(): # enclosed
  z = 4 
  print("outer function z: ", z)
  def inner(): # local
    s = 4
    print("inner s =", s)
    print("y =", y)
  inner()
outer()
#print(s) will show error as out of scope of function 
print("global", y)

outer function z:  4
inner s = 4
y = 10
global 10


In [ ]:
import math as mt 
r = mt.sqrt(64) 
print(r)

8.0


In [ ]:
# 2. Using from keyword 
from math import ceil 
ceil(6.6)

7

In [ ]:
# to import all the functions from your module, write * 
from math import *

In [ ]:
import random
# random function it gives a random number between 0 and 1
random.random()


0.1863449801368069

In [ ]:
# randint(a,b) it gives a random number between a and b
random.randint(15,100)

39

In [ ]:
#import time module 
from datetime import time 
a = time() 
print("a =", a) 
b = time(9, 32, 52)
print("hour", b.hour)
print("minute =", b.minute)
print("second = ", b.second)
import time
print(time.localtime (time.time()))
import datetime
print(datetime.datetime.now()) # print current date and time
#import datetime
print(datetime.date.today()) # print current date
from datetime import date
print(date.today())
dd = date.today() 
print("year", dd.year)
print("year", dd.month)
print("year", dd.day)

a = 00:00:00
hour 9
minute = 32
second =  52
time.struct_time(tm_year=2022, tm_mon=7, tm_mday=15, tm_hour=8, tm_min=30, tm_sec=8, tm_wday=4, tm_yday=196, tm_isdst=0)
2022-07-15 08:30:08.013324
2022-07-15
2022-07-15
year 2022
year 7
year 15


#15-07-2022, Friday

In [ ]:
a = 10
b = a
c = b
print(a, id(a), '\n', b, id(b), '\n', c, id(c))

10 11256352 
 10 11256352 
 10 11256352


#18-07-2022, Monday

In [ ]:
import numpy as np
nn1 = np.arange(24).reshape(4, 3, 2)
print(nn1)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [ ]:
# Using universal function:

n3 = np.add(nn1, nn2)
print(n3)

#19-07-2022, Tuesday

In [ ]:
import numpy as np
url = 'https://raw.githubusercontent.com/ahkhaider-10/Python/master/ClassExamples/PJ121/Wines/winequality-red.csv'

wfile = np.genfromtxt(url, delimiter = ';', skip_header = 1)
wfile

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [ ]:
# wfile[2:7, 0:3]
# wfile[2:7].max()
wfile[2:7]

array([[7.800e+00, 7.600e-01, 4.000e-02, 2.300e+00, 9.200e-02, 1.500e+01,
        5.400e+01, 9.970e-01, 3.260e+00, 6.500e-01, 9.800e+00, 5.000e+00],
       [1.120e+01, 2.800e-01, 5.600e-01, 1.900e+00, 7.500e-02, 1.700e+01,
        6.000e+01, 9.980e-01, 3.160e+00, 5.800e-01, 9.800e+00, 6.000e+00],
       [7.400e+00, 7.000e-01, 0.000e+00, 1.900e+00, 7.600e-02, 1.100e+01,
        3.400e+01, 9.978e-01, 3.510e+00, 5.600e-01, 9.400e+00, 5.000e+00],
       [7.400e+00, 6.600e-01, 0.000e+00, 1.800e+00, 7.500e-02, 1.300e+01,
        4.000e+01, 9.978e-01, 3.510e+00, 5.600e-01, 9.400e+00, 5.000e+00],
       [7.900e+00, 6.000e-01, 6.000e-02, 1.600e+00, 6.900e-02, 1.500e+01,
        5.900e+01, 9.964e-01, 3.300e+00, 4.600e-01, 9.400e+00, 5.000e+00]])

#20-07-2022, Wednesday


In [ ]:
# %timeit sum([1, 2, 3, 4, 5])
# plt.hist(arr1)

#21-07-2022, Thursday